#!/bin/bash

PULLSECRET=ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJjM2x6WkdsbksyRnNiMnRoWjJkaGNuZGhiRG8xU1Vjek9GYzNOVXRYUkRjeVNVMHdVMGswUzA1RVZ6UTBVMDh3T1ZveFIxYzNNVGRaVUZsV1JGWklWVTVKT0ZVNFJqZEpXVU5YVVZnMFZsVkdTbE5NIiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=

echo $PULLSECRET | base64 -d | awk NR==4 | cut -d'"' -f4 | xargs | base64 -d
echo $'\n'
